# Generated by Django 5.2.17 on 2026-08-19 10:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                ("object_id", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=40)),
                ("actor", models.CharField(max_length=64)),
                ("reason", models.CharField(blank=True, max_length=240)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=40)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Uom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("code", models.CharField(max_length=16, unique=True)),
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[^A-Za-z]+$", "计量单位必须使用规范中文/本地化名称"
                            )
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=160)),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "min_pack_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "min_ship_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                ("tax_number", models.CharField(blank=True, max_length=32)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="backend.currency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("warehouse", "仓库"),
                            ("fg", "成品库"),
                            ("rm", "原料库"),
                            ("wip", "在制品库"),
                            ("ng", "不良品库"),
                            ("virtual", "虚拟库"),
                        ],
                        default="warehouse",
                        max_length=16,
                    ),
                ),
                ("manager", models.CharField(blank=True, max_length=64)),
                ("warehouse_code", models.CharField(blank=True, max_length=32)),
                ("participate_mrp", models.BooleanField(default=True)),
                ("usable", models.BooleanField(default=True)),
                ("allow_negative", models.BooleanField(default=False)),
                ("quarantine_return", models.BooleanField(default=False)),
                ("storage_account", models.CharField(blank=True, max_length=32)),
                ("material_account", models.CharField(blank=True, max_length=32)),
                (
                    "outsource_material_account",
                    models.CharField(blank=True, max_length=32),
                ),
                ("sales_income_account", models.CharField(blank=True, max_length=32)),
                ("sales_cost_account", models.CharField(blank=True, max_length=32)),
                ("department", models.CharField(blank=True, max_length=64)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="backend.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("code", models.CharField(blank=True, max_length=40, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("english_name", models.CharField(blank=True, max_length=160)),
                ("old_code", models.CharField(blank=True, max_length=40)),
                ("customs_code", models.CharField(blank=True, max_length=40)),
                ("customs_name", models.CharField(blank=True, max_length=160)),
                ("barcode", models.CharField(blank=True, max_length=80)),
                ("tax_code", models.CharField(max_length=32)),
                ("tax_name", models.CharField(blank=True, max_length=160)),
                ("invoice_name", models.CharField(blank=True, max_length=160)),
                ("purpose", models.CharField(blank=True, max_length=240)),
                ("active", models.BooleanField(default=True)),
                ("join_date", models.DateField(blank=True, null=True)),
                ("part_type", models.CharField(blank=True, max_length=80)),
                ("product_group", models.CharField(blank=True, max_length=80)),
                ("engineering_reviewer", models.CharField(blank=True, max_length=64)),
                ("specification", models.TextField(blank=True)),
                ("carton_mark", models.TextField(blank=True)),
                (
                    "gross_weight_g",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "net_weight_g",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=40)),
                ("drawing_number", models.CharField(blank=True, max_length=80)),
                (
                    "scrap_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "products_per_carton",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="materials/")),
                (
                    "default_storage_position",
                    models.CharField(blank=True, max_length=80),
                ),
                ("batch_control", models.BooleanField(default=False)),
                ("batch_rule", models.CharField(blank=True, max_length=80)),
                ("abc_class", models.CharField(blank=True, max_length=8)),
                ("count_cycle_days", models.PositiveIntegerField(default=0)),
                ("shelf_life_days", models.PositiveIntegerField(default=0)),
                ("warehouse_manager", models.CharField(blank=True, max_length=64)),
                (
                    "safety_stock_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "max_stock_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "stock_warning_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("production_lead_days", models.PositiveIntegerField(default=0)),
                ("purchase_lead_days", models.PositiveIntegerField(default=0)),
                (
                    "quality_control",
                    models.CharField(default="required", max_length=20),
                ),
                ("quality_lead_days", models.PositiveIntegerField(default=0)),
                ("supply_method", models.CharField(default="purchase", max_length=20)),
                ("phantom", models.BooleanField(default=False)),
                ("roll", models.BooleanField(default=False)),
                (
                    "min_purchase_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "min_pack_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "min_issue_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("receipt_consume_mode", models.CharField(blank=True, max_length=40)),
                (
                    "outsource_receipt_consume_mode",
                    models.CharField(blank=True, max_length=40),
                ),
                ("buyer", models.CharField(blank=True, max_length=64)),
                ("planner", models.CharField(blank=True, max_length=64)),
                ("production_line", models.CharField(blank=True, max_length=80)),
                ("order_strategy", models.CharField(blank=True, max_length=40)),
                (
                    "order_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("order_period_days", models.PositiveIntegerField(default=0)),
                (
                    "over_receipt_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("default_operation", models.PositiveIntegerField(default=0)),
                ("scheduling_class", models.CharField(blank=True, max_length=80)),
                ("low_level_code", models.PositiveIntegerField(default=0)),
                ("plan_order", models.BooleanField(default=True)),
                ("non_production", models.BooleanField(default=False)),
                ("purchase_quote_unrestricted", models.BooleanField(default=False)),
                ("sales_quote_unrestricted", models.BooleanField(default=False)),
                ("issue_qty_unrestricted", models.BooleanField(default=False)),
                (
                    "outsource_surplus_excluded_from_mrp",
                    models.BooleanField(default=False),
                ),
                ("no_stock_movement", models.BooleanField(default=False)),
                (
                    "default_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_materials",
                        to="backend.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.company",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.material",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="used_in_companies",
            field=models.ManyToManyField(
                related_name="materials",
                through="backend.MaterialCompany",
                to="backend.company",
            ),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("customer", "客户"),
                            ("supplier", "供应商"),
                            ("both", "客户及供应商"),
                        ],
                        max_length=12,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=240)),
                ("invoice_address", models.CharField(blank=True, max_length=240)),
                ("delivery_address", models.CharField(blank=True, max_length=240)),
                ("operating_address", models.CharField(blank=True, max_length=240)),
                ("website", models.URLField(blank=True)),
                ("business_owner", models.CharField(blank=True, max_length=64)),
                ("payment_method", models.CharField(blank=True, max_length=80)),
                ("payment_method_2", models.CharField(blank=True, max_length=80)),
                ("payment_method_3", models.CharField(blank=True, max_length=80)),
                ("payment_terms", models.CharField(blank=True, max_length=80)),
                ("quote_method", models.CharField(blank=True, max_length=40)),
                ("invoice_type", models.CharField(blank=True, max_length=40)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("100"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("tax_number", models.CharField(blank=True, max_length=32)),
                ("legal_person", models.CharField(blank=True, max_length=80)),
                (
                    "registered_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                ("opening_date", models.DateField(blank=True, null=True)),
                (
                    "service_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=40)),
                ("region", models.CharField(blank=True, max_length=80)),
                ("sales_person", models.CharField(blank=True, max_length=64)),
                ("payment_bank", models.CharField(blank=True, max_length=120)),
                ("bank_account", models.CharField(blank=True, max_length=80)),
                ("business_type", models.CharField(blank=True, max_length=40)),
                ("credit_policy", models.CharField(blank=True, max_length=80)),
                (
                    "credit_limit_1",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "credit_limit_2",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("overdue_days_1", models.PositiveIntegerField(default=0)),
                ("overdue_days_2", models.PositiveIntegerField(default=0)),
                ("deposit_account", models.CharField(blank=True, max_length=32)),
                ("receivable_account", models.CharField(blank=True, max_length=32)),
                ("income_account", models.CharField(blank=True, max_length=32)),
                ("cost_account", models.CharField(blank=True, max_length=32)),
                ("purchase_account", models.CharField(blank=True, max_length=32)),
                (
                    "temporary_payable_account",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "outsource_material_account",
                    models.CharField(blank=True, max_length=32),
                ),
                ("supplier_type", models.CharField(blank=True, max_length=32)),
                ("material_price_method", models.CharField(blank=True, max_length=40)),
                (
                    "material_price_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "backup_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "over_receipt_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("internal_company", models.BooleanField(default=False)),
                ("payment_hold", models.BooleanField(default=False)),
                ("consignment", models.BooleanField(default=False)),
                ("credit_enabled", models.BooleanField(default=True)),
                ("business_type_code", models.CharField(blank=True, max_length=40)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partners",
                        to="backend.currency",
                    ),
                ),
                (
                    "default_receipt_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_partner_receipts",
                        to="backend.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="material",
            name="default_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_materials",
                to="backend.partner",
            ),
        ),
        migrations.CreateModel(
            name="PartnerBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(default="company", max_length=20)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("account_name", models.CharField(blank=True, max_length=120)),
                ("account_number", models.CharField(max_length=80)),
                ("bank_code", models.CharField(blank=True, max_length=32)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="backend.partner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.company",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.partner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="partner",
            name="companies",
            field=models.ManyToManyField(
                related_name="partners",
                through="backend.PartnerCompany",
                to="backend.company",
            ),
        ),
        migrations.CreateModel(
            name="PartnerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("position", models.CharField(blank=True, max_length=80)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("fax", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="backend.partner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("code_prefix", models.CharField(blank=True, max_length=16)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="backend.productcategory",
                    ),
                ),
                (
                    "default_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_categories",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materials",
                to="backend.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="SupplierQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("number", models.CharField(blank=True, max_length=40, unique=True)),
                (
                    "quote_type",
                    models.CharField(
                        choices=[("purchase", "采购报价"), ("outsource", "外协报价")],
                        max_length=16,
                    ),
                ),
                ("tax_included", models.BooleanField(default=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "material_unit_price",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "processing_unit_price",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "min_purchase_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "min_pack_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=240)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_quotes",
                        to="backend.currency",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_quotes",
                        to="backend.material",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_quotes",
                        to="backend.partner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierQuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_qty",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "material_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "processing_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=240)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="backend.supplierquote",
                    ),
                ),
            ],
            options={
                "ordering": ("min_qty",),
            },
        ),
        migrations.CreateModel(
            name="MaterialUomConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("engineering", "工程BOM"),
                            ("production", "生产领用"),
                            ("purchase", "采购"),
                            ("sales", "销售"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "business_qty",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "stock_qty",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uom_conversions",
                        to="backend.material",
                    ),
                ),
                (
                    "business_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_conversions",
                        to="backend.uom",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materials",
                to="backend.uom",
            ),
        ),
        migrations.CreateModel(
            name="CustomerMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_code", models.CharField(max_length=80)),
                ("customer_name", models.CharField(blank=True, max_length=160)),
                (
                    "customer_specification",
                    models.CharField(blank=True, max_length=240),
                ),
                ("customer_barcode", models.CharField(blank=True, max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=240)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_materials",
                        to="backend.material",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_materials",
                        to="backend.partner",
                    ),
                ),
                (
                    "customer_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_materials",
                        to="backend.uom",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="uom",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uoms",
                to="backend.uomcategory",
            ),
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "rate_to_company",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="backend.currency",
                    ),
                ),
            ],
            options={
                "ordering": ("-effective_date",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("currency", "effective_date"),
                        name="uniq_currency_rate_start",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="materialcompany",
            constraint=models.UniqueConstraint(
                fields=("material", "company"), name="uniq_material_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="partnercompany",
            constraint=models.UniqueConstraint(
                fields=("partner", "company"), name="uniq_partner_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierquoteline",
            constraint=models.UniqueConstraint(
                fields=("quote", "min_qty"), name="uniq_quote_min_qty"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialuomconversion",
            constraint=models.UniqueConstraint(
                fields=("material", "usage"), name="uniq_material_uom_usage"
            ),
        ),
        migrations.AddConstraint(
            model_name="customermaterial",
            constraint=models.UniqueConstraint(
                fields=("customer", "customer_code"),
                name="uniq_customer_external_material",
            ),
        ),
    ]
