# Generated by Django 5.2.17 on 2026-08-20 04:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="company",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="currency",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="currency",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="currencyrate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="currencyrate",
            name="updated_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="location",
            name="approval_permissions",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="location",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="location",
            name="disabled_for_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="inspection_reject_return_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="material",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partner",
            name="after_sales_income_account",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="partner",
            name="after_sales_method",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="partner",
            name="business_license",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partner",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="partner",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partner",
            name="monthly_close_day",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partner",
            name="over_order_delivery_ratio",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="parent_company",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="partner",
            name="price_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="partner",
            name="quoted_settlement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partner",
            name="round_order_quantity_for_tier_price",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partner",
            name="tax_calculation_method",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="partner",
            name="tax_category",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="partner",
            name="three_certificates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partner",
            name="view_permission",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="batch_control",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="batch_rule",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="business_cost_account",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="business_income_account",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="buyer",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="default_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_categories",
                to="backend.location",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="inventory_account",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="issue_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="key_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="main_production_plan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="material_approval_permissions",
            field=models.CharField(default="*", max_length=240),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="material_code_rule",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="material_delete_permissions",
            field=models.CharField(default="*", max_length=240),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="material_edit_permissions",
            field=models.CharField(default="*", max_length=240),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="material_view_permissions",
            field=models.CharField(default="*", max_length=240),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="non_stock_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="outsource_material_account",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="part_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="phantom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="print_permission",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="product_group",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="production_cost_account",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="quality_control",
            field=models.CharField(default="exempt", max_length=20),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="roll",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="supply_method",
            field=models.CharField(default="purchase", max_length=20),
        ),
        migrations.AddField(
            model_name="supplierquote",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierquote",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="supplierquote",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uom",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uom",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="uom",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uomcategory",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uomcategory",
            name="confirmed_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="uomcategory",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
