# Generated by Django 5.2.17 on 2026-08-20 10:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_approval_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_by", models.CharField(blank=True, max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("version", models.CharField(default="A", max_length=20)),
                (
                    "effective_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("kind", models.CharField(blank=True, max_length=20)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("source_object", models.CharField(default="bom_mstr", max_length=40)),
                (
                    "parent_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boms",
                        to="backend.material",
                    ),
                ),
            ],
            options={
                "ordering": ("parent_material__code", "-effective_date", "version"),
            },
        ),
        migrations.CreateModel(
            name="BomLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "scrap_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("operation", models.PositiveIntegerField(default=0)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("source_object", models.CharField(default="ps_mstr", max_length=40)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="backend.billofmaterial",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_component_lines",
                        to="backend.material",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("bom", "line_number"),
            },
        ),
        migrations.AddConstraint(
            model_name="billofmaterial",
            constraint=models.UniqueConstraint(
                fields=("parent_material", "version"), name="uniq_material_bom_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="bomline",
            constraint=models.UniqueConstraint(
                fields=("bom", "line_number"), name="uniq_bom_line_number"
            ),
        ),
    ]
