# Generated by Django 5.2.17 on 2026-08-20 10:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_bom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Routing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_by", models.CharField(blank=True, max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=40)),
                ("version", models.CharField(default="A", max_length=20)),
                (
                    "effective_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=240)),
                (
                    "source_object",
                    models.CharField(default="route_mstr", max_length=40),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routings",
                        to="backend.material",
                    ),
                ),
            ],
            options={
                "ordering": ("material__code", "version"),
            },
        ),
        migrations.CreateModel(
            name="RoutingOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("work_center", models.CharField(max_length=40)),
                (
                    "run_time",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "production_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "yield_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("100"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("tool", models.CharField(blank=True, max_length=80)),
                ("parameters", models.CharField(blank=True, max_length=240)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("is_default", models.BooleanField(default=False)),
                ("is_alternate", models.BooleanField(default=False)),
                ("alternate_sequence", models.PositiveIntegerField(default=0)),
                ("operation_type", models.CharField(default="internal", max_length=20)),
                ("source_object", models.CharField(default="ro_det", max_length=40)),
                (
                    "purchase_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outsource_operations",
                        to="backend.material",
                    ),
                ),
                (
                    "routing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="backend.routing",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routing_operations",
                        to="backend.partner",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routing_operations",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("routing", "sequence"),
            },
        ),
        migrations.AddConstraint(
            model_name="routing",
            constraint=models.UniqueConstraint(
                fields=("material", "version"), name="uniq_material_routing_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="routingoperation",
            constraint=models.UniqueConstraint(
                fields=("routing", "sequence"), name="uniq_routing_operation_sequence"
            ),
        ),
    ]
