# Generated by Django 5.2.17 on 2026-08-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_routing"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="source_object",
            field=models.CharField(default="loc_mstr", max_length=40),
        ),
        migrations.AddField(
            model_name="location",
            name="source_site",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_by", models.CharField(blank=True, max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=240)),
                ("manager", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("source_object", models.CharField(default="si_mstr", max_length=40)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouses",
                        to="backend.company",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.AddField(
            model_name="location",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="backend.warehouse",
            ),
        ),
    ]
