# Generated by Django 5.2.17 on 2026-08-20 10:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_sales_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_by", models.CharField(blank=True, max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=40, unique=True)),
                (
                    "request_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("needed_date", models.DateField()),
                (
                    "aggregation_mode",
                    models.CharField(
                        choices=[("none", "不汇总"), ("material", "按物料汇总")],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("quantity_rule", models.CharField(default="mrp", max_length=16)),
                ("only_positive", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("source_object", models.CharField(default="pr_mstr", max_length=40)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisitions",
                        to="backend.department",
                    ),
                ),
                (
                    "source_sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisitions",
                        to="backend.salesorder",
                    ),
                ),
            ],
            options={
                "ordering": ("-request_date", "-number"),
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                (
                    "mrp_demand_qty",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "on_order_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "available_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "safety_stock_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "requested_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        editable=False,
                        max_digits=18,
                    ),
                ),
                (
                    "calculation_snapshot",
                    models.JSONField(default=dict, editable=False),
                ),
                (
                    "converted_qty",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("source_object", models.CharField(default="req_mstr", max_length=40)),
                (
                    "source_detail_object",
                    models.CharField(default="reqd_det", max_length=40),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisition_lines",
                        to="backend.material",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="backend.purchaserequisition",
                    ),
                ),
                (
                    "source_sales_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisition_lines",
                        to="backend.salesorderline",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisition_lines",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("requisition", "line_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("requisition", "line_number"),
                        name="uniq_purchase_requisition_line",
                    )
                ],
            },
        ),
    ]
