# Generated by Django 5.2.17 on 2026-08-20 10:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_purchasing"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_by", models.CharField(blank=True, max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=40, unique=True)),
                (
                    "receipt_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("normal", "采购收货"),
                            ("non_production", "非生产收货"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("posted", models.BooleanField(default=False, editable=False)),
                ("source_object", models.CharField(default="grn_mstr", max_length=40)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="backend.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="backend.partner",
                    ),
                ),
            ],
            options={
                "ordering": ("-receipt_date", "-number"),
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "accepted_quantity",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "rejected_quantity",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=80)),
                ("source_object", models.CharField(default="grnd_det", max_length=40)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="backend.location",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="backend.material",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="backend.purchaseorderline",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="backend.goodsreceipt",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("receipt", "line_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt", "line_number"),
                        name="uniq_goods_receipt_line",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=80)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="backend.location",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="backend.material",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balances",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("material__code", "location__code", "batch_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("material", "location", "batch_number"),
                        name="uniq_stock_balance_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_type", models.CharField(max_length=24)),
                ("batch_number", models.CharField(blank=True, max_length=80)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("balance_after", models.DecimalField(decimal_places=6, max_digits=18)),
                ("source_model", models.CharField(max_length=80)),
                ("source_id", models.CharField(max_length=64)),
                ("source_line_id", models.CharField(max_length=64)),
                ("actor", models.CharField(max_length=64)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="backend.location",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="backend.material",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("-posted_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_model",
                            "source_line_id",
                            "movement_type",
                            "location",
                        ),
                        name="uniq_stock_source_movement",
                    )
                ],
            },
        ),
    ]
