# Generated by Django 5.2.17 on 2026-08-20 10:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_inventory_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_by", models.CharField(blank=True, max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=40, unique=True)),
                (
                    "delivery_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("delivery_address", models.CharField(max_length=240)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[("direct", "直送"), ("supplier", "供应商代送")],
                        default="direct",
                        max_length=16,
                    ),
                ),
                ("srm_number", models.CharField(max_length=80)),
                ("customer_po", models.CharField(max_length=80)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("actual_ship_time", models.DateTimeField(blank=True, null=True)),
                ("posted", models.BooleanField(default=False, editable=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_orders",
                        to="backend.partner",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_orders",
                        to="backend.salesorder",
                    ),
                ),
            ],
            options={
                "ordering": ("-delivery_date", "-number"),
            },
        ),
        migrations.CreateModel(
            name="DeliveryOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=80)),
                ("srm_customer_po", models.CharField(max_length=80)),
                ("srm_material_code", models.CharField(max_length=80)),
                ("srm_material_name", models.CharField(max_length=160)),
                (
                    "srm_quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "customer_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_lines",
                        to="backend.customermaterial",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="backend.deliveryorder",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_order_lines",
                        to="backend.material",
                    ),
                ),
                (
                    "sales_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_lines",
                        to="backend.salesorderline",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_lines",
                        to="backend.location",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_order_lines",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("delivery", "line_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("delivery", "line_number"),
                        name="uniq_delivery_order_line",
                    )
                ],
            },
        ),
    ]
