# Generated by Django 5.2.17 on 2026-08-20 11:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_stock_control"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("rejected", "已驳回"),
                            ("void", "已作废"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.CharField(blank=True, max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=240)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_by", models.CharField(blank=True, max_length=64)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=40, unique=True)),
                (
                    "return_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("replenishment", models.BooleanField(default=True)),
                ("reason", models.CharField(max_length=240)),
                ("posted", models.BooleanField(default=False, editable=False)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_returns",
                        to="backend.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_returns",
                        to="backend.partner",
                    ),
                ),
            ],
            options={
                "ordering": ("-return_date", "-number"),
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="source_purchase_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_orders",
                to="backend.purchasereturn",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=80)),
                ("reason", models.CharField(max_length=240)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_return_lines",
                        to="backend.material",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="backend.purchaseorderline",
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="backend.purchasereturn",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_return_lines",
                        to="backend.location",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_return_lines",
                        to="backend.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("purchase_return", "line_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("purchase_return", "line_number"),
                        name="uniq_purchase_return_line",
                    )
                ],
            },
        ),
    ]
