# Generated by Django 5.2.17 on 2026-08-21 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_payable_vouchers"),
    ]

    operations = [
        migrations.AddField(
            model_name="payablevoucherline",
            name="source_purchase_return_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payable_voucher_line",
                to="backend.purchasereturnline",
            ),
        ),
        migrations.AlterField(
            model_name="payablevoucherline",
            name="source_receipt_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payable_voucher_line",
                to="backend.goodsreceiptline",
            ),
        ),
        migrations.AddConstraint(
            model_name="payablevoucherline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_purchase_return_line__isnull", True),
                        ("source_receipt_line__isnull", False),
                    ),
                    models.Q(
                        ("source_purchase_return_line__isnull", False),
                        ("source_receipt_line__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payable_line_exactly_one_source",
            ),
        ),
    ]
