# Generated by Django 5.2.17 on 2026-08-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_taxcode_material_tax_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_attribute',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
