# Generated by Django 5.2.17 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_partner_field_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="supplier_delivery_number",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
