# Generated by Django 5.2.17 on 2026-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_align_goods_receipt_source_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=40)),
                ('document_id', models.PositiveIntegerField()),
                ('document_number', models.CharField(blank=True, max_length=80)),
                ('evidence_type', models.CharField(choices=[('supplier_delivery', '供应商送货签收单'), ('customer_delivery', '客户送货签收单'), ('customer_return', '客户退货单'), ('warehouse_return', '仓库退货单')], max_length=32)),
                ('file', models.FileField(upload_to='document_evidence/')),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('uploaded_by', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-uploaded_at', '-id'),
                'indexes': [models.Index(fields=['document_type', 'document_id'], name='evidence_document_idx')],
            },
        ),
    ]
