# Generated by Django 5.2.17 on 2026-08-26

from decimal import Decimal

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0025_document_evidence"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customermaterial",
            name="uniq_customer_external_material",
        ),
        migrations.AddField(
            model_name="customermaterial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customermaterial",
            name="created_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customermaterial",
            name="customer_uom_rate_d",
            field=models.DecimalField(decimal_places=6, default=Decimal("1"), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.000001"))]),
        ),
        migrations.AddField(
            model_name="customermaterial",
            name="customer_uom_rate_m",
            field=models.DecimalField(decimal_places=6, default=Decimal("1"), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.000001"))]),
        ),
        migrations.AddField(
            model_name="customermaterial",
            name="terminal_customer_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="customermaterial",
            name="terminal_customer_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="customermaterial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customermaterial",
            name="updated_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="customermaterial",
            constraint=models.UniqueConstraint(fields=("customer", "material", "customer_code"), name="uniq_customer_material_external_code"),
        ),
    ]
