# Generated by Django 5.2.17 on 2026-08-26 08:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_merge_location_quarantine_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuoteSequence',
            fields=[
                ('period', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='salesquote',
            options={'ordering': ('-effective_date', '-number')},
        ),
        migrations.RenameField(
            model_name='salesquote',
            old_name='quote_date',
            new_name='effective_date',
        ),
        migrations.AddField(
            model_name='partner',
            name='quote_tax_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='backup_ratio',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='discount_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('100'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='is_ratified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='modification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='ratified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='ratified_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='source_object',
            field=models.CharField(default='sc_mstr', max_length=40),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='tax_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='usage',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='customer_material_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='customer_material_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='material_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='material_specification',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='terminal_customer_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='terminal_customer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='uom_rate_d',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='uom_rate_m',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='customermaterial',
            name='customer_uom_rate_d',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='customermaterial',
            name='customer_uom_rate_m',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='backup_ratio',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='discount_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('100'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesquoteline',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='salesquoteline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesquoteline',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='SalesQuoteTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('min_quantity', models.DecimalField(decimal_places=8, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('backup_ratio', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modification_count', models.PositiveIntegerField(default=0)),
                ('source_object', models.CharField(default='scd_det', max_length=40)),
                ('quote_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='backend.salesquoteline')),
            ],
            options={
                'ordering': ('quote_line', 'min_quantity', 'line_number'),
                'constraints': [models.UniqueConstraint(fields=('quote_line', 'line_number'), name='uniq_sales_quote_tier_line'), models.UniqueConstraint(fields=('quote_line', 'min_quantity'), name='uniq_sales_quote_tier_threshold')],
            },
        ),
    ]
