# Generated by Django 5.2.17 on 2026-08-27 06:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def backfill_supplier_quote_fields(apps, schema_editor):
    SupplierQuote = apps.get_model('backend', 'SupplierQuote')
    SupplierQuoteLine = apps.get_model('backend', 'SupplierQuoteLine')
    MaterialUomConversion = apps.get_model('backend', 'MaterialUomConversion')
    for quote in SupplierQuote.objects.select_related('material').iterator():
        conversion = MaterialUomConversion.objects.filter(material_id=quote.material_id, usage='purchase').first()
        quote.purchase_uom_id = conversion.business_uom_id if conversion else quote.material.uom_id
        quote.uom_rate_m = conversion.business_qty if conversion else Decimal('1')
        quote.uom_rate_d = conversion.stock_qty if conversion else Decimal('1')
        quote.unit_price = quote.material_unit_price + quote.processing_unit_price
        quote.save(update_fields=('purchase_uom', 'uom_rate_m', 'uom_rate_d', 'unit_price'))
        for line_number, line in enumerate(SupplierQuoteLine.objects.filter(quote_id=quote.pk).order_by('min_qty', 'pk'), 1):
            line.line_number = line_number
            line.unit_price = (line.material_unit_price or Decimal('0')) + (line.processing_unit_price or Decimal('0'))
            line.save(update_fields=('line_number', 'unit_price'))


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_salesquotesequence_alter_salesquote_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQuoteSequence',
            fields=[
                ('period', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='supplierquote',
            options={'ordering': ('-effective_date', '-number')},
        ),
        migrations.AlterModelOptions(
            name='supplierquoteline',
            options={'ordering': ('quote', 'min_qty', 'line_number')},
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='source_supplier_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='backend.supplierquote'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='source_supplier_quote_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='backend.supplierquoteline'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='delivery_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='is_ratified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='is_sales_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='modification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotes', to='backend.routingoperation'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='parent_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outsource_supplier_quotes', to='backend.material'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotes', to='backend.uom'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='ratified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='ratified_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='sales_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='sales_confirmed_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='source_object',
            field=models.CharField(default='pc_mstr', max_length=40),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='uom_rate_d',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='uom_rate_m',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='workflow_status',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='created_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='line_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='modification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='source_object',
            field=models.CharField(default='pcd_det', max_length=40),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='updated_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='material_unit_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='min_pack_qty',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='min_purchase_qty',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='processing_unit_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='supplierquoteline',
            name='material_unit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='supplierquoteline',
            name='min_qty',
            field=models.DecimalField(decimal_places=8, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='supplierquoteline',
            name='processing_unit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.RunPython(backfill_supplier_quote_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='supplierquoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'line_number'), name='uniq_supplier_quote_line'),
        ),
    ]
