# Generated by Django 5.2.17 on 2026-08-27 08:38

import django.db.models.deletion
from django.db import migrations, models


def seed_legacy_business_groups(apps, schema_editor):
    BusinessGroup = apps.get_model('backend', 'BusinessGroup')
    for code, name in (
        ('01', '业务一部'),
        ('02', '业务二部'),
        ('03', '业务三部'),
        ('04', 'CNC事业部'),
    ):
        BusinessGroup.objects.update_or_create(
            code=code,
            defaults={
                'name': name, 'active': True, 'status': 'approved',
                'created_by': 'system', 'updated_by': 'system',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_supplierquotesequence_alter_supplierquote_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('rejected', '已驳回'), ('void', '已作废')], default='draft', max_length=16)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=240)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_by', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='business_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotes', to='backend.businessgroup'),
        ),
        migrations.RunPython(seed_legacy_business_groups, migrations.RunPython.noop),
    ]
