# Generated by Django 5.2.17 on 2026-08-29 06:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_salesorder_tax_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderSequence',
            fields=[
                ('period', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='address_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='address_snapshot',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='document_type',
            field=models.CharField(choices=[('normal', '正常送货'), ('return', '正常退货'), ('red_flush', '红冲单据')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='source_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_flushes', to='backend.deliveryorder'),
        ),
        migrations.AddField(
            model_name='deliveryorderline',
            name='actual_spare_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='deliveryorderline',
            name='ordered_spare_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='deliveryorderline',
            name='source_delivery_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_flush_lines', to='backend.deliveryorderline'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='spare_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='backend.salesorder'),
        ),
    ]
