# Generated by Django 5.2.17 on 2026-08-29 06:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_delivery_order_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='delivered_spare_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=240)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('enabled', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_addresses', to='backend.partner')),
            ],
            options={
                'ordering': ('customer__code', 'code'),
                'constraints': [models.UniqueConstraint(fields=('customer', 'code'), name='uniq_customer_address_code')],
            },
        ),
    ]
