# Generated by Django 5.2.17 on 2026-08-29 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_delivery_order_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='default_print_person',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='backend.location'),
        ),
    ]
