# Generated by Django 5.2.17 on 2026-08-29 09:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_deliveryorder_default_print_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('rejected', '已驳回'), ('void', '已作废')], default='draft', max_length=16)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=240)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_by', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_date_method', models.CharField(choices=[('1', '月结日'), ('2', '发票日'), ('3', '指定日期')], default='1', max_length=1)),
                ('discount_percent', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_days', models.IntegerField(default=0)),
                ('discount_start_day', models.IntegerField(default=0)),
                ('due_date_method', models.CharField(choices=[('1', '月结日'), ('2', '发票日'), ('3', '指定日期')], default='1', max_length=1)),
                ('due_days', models.IntegerField(default=0)),
                ('due_start_day', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='payment_method_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='backend.paymentmethod'),
        ),
    ]
