# Generated by Django 5.2.17 on 2026-08-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_customer_address_audit_and_sales_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('rejected', '已驳回'), ('void', '已作废')], default='draft', max_length=16)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=240)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_by', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('group_code', models.CharField(blank=True, max_length=32)),
                ('department_code', models.CharField(blank=True, max_length=32)),
                ('default_site', models.CharField(blank=True, max_length=16)),
                ('is_employee', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_left', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qq', models.CharField(blank=True, max_length=30)),
                ('wechat', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('source_object', models.CharField(default='usr_mstr', max_length=40)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='business_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='backend.businessgroup'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_buyer',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_type',
            field=models.CharField(choices=[('1', '正式订单'), ('2', '样品订单')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='backend.paymentmethod'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='backend.employee'),
        ),
    ]
