# Generated by Django 5.2.17 on 2026-09-02 03:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_employee_salesorder_business_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='after_sales_method',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='after_sales_method_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='cartons',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='closed_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='configuration_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='configuration_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='configuration_approved_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='copper_currency',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='copper_origin',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='copper_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='created_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='customer_material_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='customer_material_specification',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discount_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('100'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discounted_unit_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='fixed_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='income_account',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='income_account_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='inventory_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sales_order_lines', to='backend.uom'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='line_status',
            field=models.CharField(default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='material_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='material_specification',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='modification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='price_type',
            field=models.CharField(choices=[('1', '期货价'), ('2', '期目价'), ('3', '即日价'), ('4', '议价')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='products_per_carton',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='replenishment_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='returned_spare_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='spare_ratio',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='special_configuration_requirement',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='special_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='tax_included_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='total_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='untaxed_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='untaxed_unit_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='uom_rate_d',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='uom_rate_m',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='updated_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='price_type',
            field=models.CharField(choices=[('1', '期货价'), ('2', '期目价'), ('3', '即日价'), ('4', '议价')], default='1', max_length=1),
        ),
    ]
