# Generated by Django 5.2.17 on 2026-09-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_salesorderline_after_sales_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='tax_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='tax_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='terminal_customer_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='terminal_customer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
