# Generated by Django 5.2.17 on 2026-09-02 03:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_salesorderline_invoice_name_salesorderline_tax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderline',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='delivered_spare_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='returned_spare_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='spare_quantity',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
