# Generated by Django 5.2.17 on 2026-09-02 03:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_alter_salesorderline_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderline',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='delivered_spare_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='returned_spare_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='spare_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
