# Generated by Django 5.2.17 on 2026-09-02 06:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_alter_salesorderline_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='consignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='consumption_forecast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_approved_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='forecast_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_change_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_change_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_change_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_change_confirmed_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_change_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_change_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='version',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
