# Generated by Django 5.2.17 on 2026-09-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_delivery_transaction_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='srm_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
