# Generated by Django 5.2.17 on 2026-09-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_alter_deliveryorder_srm_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderSequence',
            fields=[
                ('period', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='sales_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_lines', to='backend.salesorderline'),
        ),
    ]
