# Generated by Django 5.2.17 on 2026-09-07 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0046_salesordersequence_salesreturnline_sales_order_line"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryorderline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryorderline",
            name="created_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="deliveryorderline",
            name="modification_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deliveryorderline",
            name="source_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="deliveryorderline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryorderline",
            name="updated_by",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="deliveryorder",
            name="customer_po",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name="DeliveryNumberReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=40, unique=True)),
                ("delivery_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.deliveryorder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
