# Generated by Django 5.2.17 on 2026-09-07 09:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0047_delivery_order_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryorderline",
            name="actual_quantity",
            field=models.DecimalField(decimal_places=8, max_digits=19),
        ),
        migrations.AlterField(
            model_name="deliveryorderline",
            name="actual_spare_quantity",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("0"), max_digits=19
            ),
        ),
        migrations.AlterField(
            model_name="deliveryorderline",
            name="ordered_spare_quantity",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="deliveryorderline",
            name="srm_quantity",
            field=models.DecimalField(decimal_places=8, max_digits=19),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="delivered_quantity",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="delivered_spare_quantity",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=19,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.000001"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="returned_quantity",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="returned_spare_quantity",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="spare_quantity",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("0"),
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesreturnline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=19,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.000001"))
                ],
            ),
        ),
    ]
