import { field } from '../../app/config'

export const orderLineColumns = [
  ['line_number', '行号'],
  ['material_code', '物料编码'],
  ['customer_material_code', '客户物料编码'],
  ['material_name', '物料名称'],
  ['material_specification', '规格'],
  ['customer_material_name', '客户物料名称'],
  ['customer_material_specification', '客户物料规格'],
  ['after_sales_method', '售后服务方式'],
  ['after_sales_method_name', '售后服务方式名称'],
  ['copper_origin', '铜产地'],
  ['copper_currency', '铜币种'],
  ['copper_price', '铜价'],
  ['unit_price', '订单单价'],
  ['price_type', '单价类型'],
  ['quantity', '订购数量'],
  ['spare_quantity', '备品数量'],
  ['spare_ratio', '备品比例%'],
  ['sales_uom', '销售单位'],
  ['discounted_unit_price', '含税单价'],
  ['discount_rate', '折扣率%'],
  ['untaxed_unit_price', '未税单价'],
  ['tax_included_amount', '含税金额'],
  ['untaxed_amount', '未税金额'],
  ['special_cost', '特殊要求增加单位成本'],
  ['total_cost', '合计单位成本'],
  ['requested_date', '需求日期'],
  ['expected_delivery_date', '预计交货日期'],
  ['promised_date', '承诺交货日期'],
  ['notes', '备注'],
  ['line_status', '状态'],
  ['closed_by', '关闭人'],
  ['closed_at', '关闭时间'],
  ['fixed_price', '固定价格'],
  ['income_account', '主营业务收入科目'],
  ['income_account_name', '科目名称'],
  ['replenishment_return', '补退货'],
  ['uom_rate_m', '单位转换率(分子)'],
  ['uom_rate_d', '单位转换率(分母)'],
  ['inventory_uom', '库存单位'],
  ['delivered_quantity', '送货数量'],
  ['returned_quantity', '退货数量'],
  ['delivered_spare_quantity', '送备品数量'],
  ['returned_spare_quantity', '退备品数量'],
  ['products_per_carton', '每箱产品数'],
  ['cartons', '箱数'],
  ['special_configuration_requirement', '特殊配置要求'],
  ['configuration_approved', '配置审核'],
  ['configuration_approved_by', '配置审核人'],
  ['configuration_approved_at', '配置审核时间'],
  ['created_by', '录入人'],
  ['created_at', '录入时间'],
  ['modification_count', '修改次数'],
  ['updated_by', '最后修改人'],
  ['updated_at', '最后修改时间'],
  ['tax_code', '税务编码'],
  ['tax_name', '税务名称'],
  ['invoice_name', '开票名称'],
  ['terminal_customer_code', '终端客户料号'],
  ['terminal_customer_name', '终端客户物料名称'],
]

export const orderFields = [
  field('number', '客户订单', { kind: 'readonly' }),
  field('customer', '客户代码', { lookup: 'customers', required: true }),
  field('customer_name', '客户名称', { kind: 'readonly' }),
  field('order_type', '单别', {
    kind: 'select',
    required: true,
    options: [
      ['1', '正式订单'],
      ['2', '样品订单'],
    ],
  }),
  field('order_date', '下单日期', { kind: 'date', required: true }),
  field('customer_po', '客户 PO', { required: true }),
  field('delivery_address', '送货地址', { required: true }),
  field('address_code', '地址代码', { lookup: 'customerAddresses' }),
  field('customer_buyer', '客户采购员'),
  field('sales_person', '业务员', { lookup: 'employees' }),
  field('business_group', '业务组别', { lookup: 'businessGroups' }),
  field('srm_number', 'SRM 单号'),
  field('payment_method', '支付方式', { lookup: 'paymentMethods', kind: 'readonly' }),
  field('currency', '币种', { lookup: 'currencies', required: true, kind: 'readonly' }),
  field('exchange_rate', '汇率', { kind: 'readonly' }),
  field('tax_included', '含税', { kind: 'checkbox' }),
  field('tax_rate', '增值税率(%)', { kind: 'readonly' }),
  field('delivery_mode', '送货模式', {
    kind: 'select',
    options: [
      ['direct', '直送'],
      ['supplier', '供应商代送'],
    ],
  }),
  field('source_quote', '销售报价', { lookup: 'salesQuotes', kind: 'readonly' }),
  field('version', '版本号'),
  field('consumption_forecast', '消耗预测', { kind: 'checkbox' }),
  field('forecast_number', '预测单号'),
  field('consignment', '寄售', { kind: 'checkbox' }),
  field('promised_date', '承诺交期', { kind: 'date', required: true }),
  field('notes', '备注'),
  field('po_change_requested', '客户 PO 变更', { kind: 'readonly' }),
  field('po_change_by', '变更人', { kind: 'readonly' }),
  field('po_change_at', '变更时间', { kind: 'readonly' }),
  field('po_change_confirmed', 'PO 变更确认', { kind: 'readonly' }),
  field('po_change_confirmed_by', '确认人', { kind: 'readonly' }),
  field('po_change_confirmed_at', '确认时间', { kind: 'readonly' }),
  field('po_change_notes', '变更内容', { kind: 'readonly' }),
  field('delivery_approved', '交期审核', { kind: 'readonly' }),
  field('delivery_approved_by', '交期审核人', { kind: 'readonly' }),
  field('delivery_approved_at', '交期审核时间', { kind: 'readonly' }),
  field('print_count', '打印次数', { kind: 'readonly' }),
]

export const orderFieldByKey = Object.fromEntries(orderFields.map((item) => [item.key, item]))

export const orderGroups = [
  {
    label: '订单基本信息',
    keys: [
      'number',
      'customer',
      'customer_name',
      'order_type',
      'order_date',
      'customer_po',
      'address_code',
      'delivery_address',
      'srm_number',
    ],
  },
  {
    label: '客户与结算',
    keys: [
      'customer_buyer',
      'sales_person',
      'business_group',
      'payment_method',
      'currency',
      'exchange_rate',
      'tax_included',
      'tax_rate',
      'delivery_mode',
      'source_quote',
    ],
  },
  {
    label: '业务控制',
    keys: ['version', 'consumption_forecast', 'forecast_number', 'consignment', 'promised_date', 'notes'],
  },
  {
    label: 'PO 变更与审核',
    keys: [
      'po_change_requested',
      'po_change_by',
      'po_change_at',
      'po_change_confirmed',
      'po_change_confirmed_by',
      'po_change_confirmed_at',
      'po_change_notes',
      'delivery_approved',
      'delivery_approved_by',
      'delivery_approved_at',
      'print_count',
    ],
  },
]
