import { Factory, ListTree } from 'lucide-react'
import { config, field, numberColumn, statusColumn } from '../../app/config'
import { today } from '../../shared/presentation'

export const engineeringConfigs = {
  boms: config('BOM', 'bom', ListTree, 'bom', [['code', 'BOM代码'], ['parent_material', '父物料'], ['version', '版本'], ['effective_date', '生效日期'], statusColumn], [field('code', 'BOM代码', { required: true }), field('parent_material', '父物料', { lookup: 'materials', required: true }), field('version', '版本', { defaultValue: 'A' }), field('effective_date', '生效日期', { kind: 'date', defaultValue: today() }), field('expiry_date', '失效日期', { kind: 'date' }), field('notes', '备注')], { audited: true }),
  bomLines: config('BOM明细', 'bom-line', ListTree, 'bom', [['bom', 'BOM'], ['line_number', '行号'], ['component', '组件物料'], ['quantity', '用量'], ['operation', '工序']], [field('bom', 'BOM', { lookup: 'boms', required: true }), field('line_number', '行号', { kind: 'number', required: true }), field('component', '组件物料', { lookup: 'materials', required: true }), field('uom', '单位', { lookup: 'uoms', required: true }), field('quantity', '用量', { kind: 'number', required: true }), field('scrap_rate', '损耗率', { kind: 'number', defaultValue: 0 }), field('operation', '工序', { kind: 'number', defaultValue: 0 })]),
  routings: config('工艺路线', 'routing', Factory, 'routing', [['code', '路线代码'], ['material', '物料'], ['version', '版本'], ['effective_date', '生效日期'], statusColumn], [field('code', '路线代码', { required: true }), field('material', '物料', { lookup: 'materials', required: true }), field('version', '版本', { defaultValue: 'A' }), field('effective_date', '生效日期', { kind: 'date', defaultValue: today() }), field('expiry_date', '失效日期', { kind: 'date' }), field('notes', '备注')], { audited: true }),
  routingOperations: config('工艺工序', 'routing-operation', Factory, 'routing', [['routing', '路线'], ['sequence', '顺序'], ['name', '工序'], ['work_center', '工作中心'], ['yield_rate', '良率']], [field('routing', '工艺路线', { lookup: 'routings', required: true }), field('sequence', '顺序', { kind: 'number', required: true }), field('name', '工序名称', { required: true }), field('work_center', '工作中心', { required: true }), field('uom', '单位', { lookup: 'uoms', required: true }), field('run_time', '运行时间', { kind: 'number', defaultValue: 0 }), field('production_rate', '产能', { kind: 'number', defaultValue: 0 }), field('yield_rate', '良率%', { kind: 'number', defaultValue: 100 })]),
}

